### ISSUE TITLE
Cant run collector-agent

### ISSUE THREAD

**Issue by dv-morais** [pinpoint-apm/pinpoint-c-agent#218]
First of all, sorry for my bad english, not my first language.

# Expected Behavior

> Collector Agent up and running

# Current Behavior

> Error, cant execute "python run.py"

# Failure Information (for bugs)

Traceback (most recent call last):
  File "run.py", line 58, in <module>
    server = Server()
  File "run.py", line 44, in __init__
    self.php_agent.start()
  File "/produtos/pinpoint-c-agent-master/collector-agent/PHPAgent/FrontAgent.py", line 99, in start
    self.server.start()
  File "/produtos/pinpoint-c-agent-master/collector-agent/Events/StreamServerLayer.py", line 104, in start
    self._startAccept()
  File "/produtos/pinpoint-c-agent-master/collector-agent/Events/StreamServerLayer.py", line 107, in _startAccept
    self.listen_event = self.loop.io(self.listen.fileno(), 1)
AttributeError: 'NoneType' object has no attribute 'fileno'

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

followed the "https://github.com/naver/pinpoint-c-agent/blob/master/DOC/CollectorAgent/Readme.md" documentation, no success. It shows the error above
.
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Red Hat Enterprise Linux release 8.1 

* PHP Version: 7.4.4

* php.ini:

extension=pinpoint_php.so

pinpoint_php.DebugReport=1

pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock

pinpoint_php.SendSpanTimeOutMs=0  

pinpoint_php.TraceLimit=-1

* php-fpm or apache: apache 2.4

* collector.conf:

[Collector]

ServerType=1500

collector.grpc.agent.ip=xxxxx
collector.grpc.agent.port=9991
collector.grpc.stat.ip=xxxxx
collector.grpc.stat.port=9992
collector.grpc.span.ip=xxxxx
collector.grpc.span.port=9993
collector.grpc.discardpolicy.maxpendingthreshold=10000
[Common]
# your web server (nginx&apache) port
Web_Port=80
# debug in dev 
Log_Level=DEBUG
LOG_DIR=/produtos/agentephp/logs/
[Agent]
# the same as below "pinpoint_php.CollectorHost"
# use tcp port
# Address=dev-pinpoint-collect@port
# use unix socket
Address=unix:/tmp/collector-agent.sock

## Failure Logs

Please include any relevant log snippets or files here.

> pinpoint_log.txt  php.log  php-fpm.log etc (Anything could help us )

**Comment by eeliu** [comment]
@dv-morais  

Which type of os you used?

**Comment by dv-morais** [comment]
> @dv-morais
> 
> Which type of os you used?

Operating System: Red Hat Enterprise Linux release 8.1

**Comment by dv-morais** [comment]
@eeliu 

The error doesnt happen anymore but after running the command "run.py" there is no response... and nothing is written on the log files.... have anything that I can do?

**Comment by eeliu** [comment]
@dv-morais 

Does your app running?  Checking it with your app running

**Comment by dv-morais** [comment]
@eeliu 

![image](https://user-images.githubusercontent.com/57958197/93603077-e4abd380-f999-11ea-9459-6a2d25be86ba.png)

restarted httpd... log files are created but nothing on them.

**Comment by eeliu** [comment]
@dv-morais 
Goto "LOG_DIR=/produtos/agentephp/logs/"

**Comment by dv-morais** [comment]
###Collector-agent.log

[2020-09-18 10:20:51,764] [56307] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-18 10:20:51,764] [56307] [WARNING] [run.py:55] collector agent exit with SIGNAL
[2020-09-18 10:29:16,987] [56620] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-18 10:29:16,988] [56620] [WARNING] [run.py:55] collector agent exit with SIGNAL

the other log... empty.

**Comment by eeliu** [comment]
@dv-morais 
How about your "php.error.log"?

**Comment by dv-morais** [comment]
@eeliu 

###php_error.log

[17-Sep-2020 17:35:35 UTC] [pinpoint] [115613] [115613]catch an Error
[17-Sep-2020 17:35:35 UTC] [pinpoint] [115613] [115613]apm_error_cb called
[17-Sep-2020 21:37:53 UTC] [pinpoint] [18680] [18680]catch an Error
[17-Sep-2020 21:37:53 UTC] [pinpoint] [18680] [18680]apm_error_cb called

**Comment by eeliu** [comment]
@dv-morais 

As it said, check your application !

**Comment by dv-morais** [comment]
@eeliu 

trying again, now using the php/example.

![image](https://user-images.githubusercontent.com/57958197/94604300-d9945580-026d-11eb-9a89-8813dcb6ffb4.png)

![image](https://user-images.githubusercontent.com/57958197/94605869-12352e80-0270-11eb-9f2c-8773169688f2.png)

![image](https://user-images.githubusercontent.com/57958197/94606045-4c063500-0270-11eb-9ca6-49c401b29c63.png)

![image](https://user-images.githubusercontent.com/57958197/94606192-7eb02d80-0270-11eb-9821-e31983320830.png)

![image](https://user-images.githubusercontent.com/57958197/94606262-97204800-0270-11eb-9c1f-5a9b56fd85a1.png)



front.agent.log= empty
php_errors.log= does not exist

###collector-agent.log

[2020-09-28 17:12:45,747] [5465] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-28 17:12:45,747] [5465] [WARNING] [run.py:55] collector agent exit with SIGNAL
[2020-09-28 17:20:46,548] [5596] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-28 17:20:46,549] [5596] [WARNING] [run.py:55] collector agent exit with SIGNAL
[2020-09-28 17:24:50,203] [5688] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-28 17:24:50,203] [5688] [WARNING] [run.py:55] collector agent exit with SIGNAL
[2020-09-28 17:39:21,187] [5721] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-28 17:39:21,187] [5721] [WARNING] [run.py:55] collector agent exit with SIGNAL
[2020-09-28 18:37:49,814] [7885] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-28 18:37:49,815] [7885] [WARNING] [run.py:55] collector agent exit with SIGNAL
[2020-09-28 19:46:36,059] [2762] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-28 19:46:36,060] [2762] [WARNING] [run.py:55] collector agent exit with SIGNAL
[2020-09-28 19:50:02,566] [2886] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-28 19:50:02,567] [2886] [WARNING] [run.py:55] collector agent exit with SIGNAL
[2020-09-29 16:02:39,025] [3711] [INFO] [AppManagement.py:68] recieved 0 span from php-fpm
[2020-09-29 16:02:39,025] [3711] [WARNING] [run.py:55] collector agent exit with SIGNAL

![image](https://user-images.githubusercontent.com/57958197/94608703-267b2a80-0274-11eb-89f6-6644db8979c8.png)


I admit it, I have no idea what to do now. I'm doing something wrong and I have no clue.

**Comment by eeliu** [comment]
@dv-morais 

Share your php_error.log

**Comment by dv-morais** [comment]
@eeliu 

it's empty! Cannot find anything.


![image](https://user-images.githubusercontent.com/57958197/94850220-0034c680-03fd-11eb-8e8e-4377c6e65b11.png)

![image](https://user-images.githubusercontent.com/57958197/94850458-5c97e600-03fd-11eb-8255-410512862b98.png)

**Comment by eeliu** [comment]
According to https://github.com/naver/pinpoint-c-agent/issues/218#issuecomment-697774763

It can't be empyt, check your php.ini setting!

**Comment by dv-morais** [comment]
@eeliu 

I build a new httpd and php from scratch in a new VM.... thats why its empty.

**Comment by eeliu** [comment]
@dv-morais 

pinpoint-c-agent supports  httpd

Check this comment https://github.com/naver/pinpoint-c-agent/issues/162#issuecomment-610122778.

Share the result to us! 

Thanks

**Comment by dv-morais** [comment]
@eeliu 

finally it worked with the PHP example inside the agent.


![image](https://user-images.githubusercontent.com/57958197/95917722-150c4500-0d81-11eb-9568-df7d028860d1.png)


![image](https://user-images.githubusercontent.com/57958197/95917865-47b63d80-0d81-11eb-991c-098f2829407e.png)

**my php.ini**

> display_errors = On
> display_startup_errors = On
> extension=pinpoint_php.so
> pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock
> pinpoint_php.SendSpanTimeOutMs=0
> pinpoint_php.TraceLimit=-1
> pinpoint_php.DebugReport=true
> log_errors = On
> error_log ="/produtos/agent.log"


after this finally the log was generated and then I saw this message

>[13-Oct-2020 15:24:04 UTC] [pinpoint] [19146] [19163]pinpoint_end_trace Done!
>[13-Oct-2020 15:24:04 UTC] [pinpoint] [19146] [19163]pinpoint_start start
>[13-Oct-2020 15:24:04 UTC] [pinpoint] [19146] [19163]agent try to connect:(unix:/tmp/collector-agent.sock)
>[13-Oct-2020 15:24:04 UTC] [pinpoint] [19146] [19163]connect:(/tmp/collector-agent.sock) failed as (Permission denied)
>[13-Oct-2020 15:24:04 UTC] [pinpoint] [19146] [19163]key:uri value:/index.php?type=test_args

I gave permissions to the .sock file and it started monitoring from the example.

After that I figured out that only starting the agent isnt enough to monitor the application. After digging more on the documentation. I still need to do some implementation at the application code. Right? Seems like I wasnt understanding how this agent works at all. ugh.

anyway big THANKS for the help during all this time.
