### ISSUE TITLE
PHP Agent apm_error_cb called

### ISSUE THREAD

**Issue by pradeepgunsgmail** [pinpoint-apm/pinpoint-c-agent#221]
Hi All ,

My PHP application is not visible in PINPOINT GUI and I can see  below error on php error log

[pinpoint] [14711] [14711]catch an Error
[pinpoint] [14711] [14711]apm_error_cb called

* Operating System: CentOS 7

* PHP Version: 7.3

* php.ini: 
extension=pinpoint_php.so
pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock
pinpoint_php.SendSpanTimeOutMs=0
pinpoint_php.DebugReport=true
pinpoint_php.TraceLimit=-1
log_errors = On
error_log = "/backup/demoapp/pinpoint-c-agent/logs/agent.log"

* php-fpm or apache: Apache

* pinpoint_agent.conf:
[Collector]
ServerType=1500
collector.grpc.agent.ip=192.168.254.211
collector.grpc.agent.port=9991
collector.grpc.stat.ip=192.168.254.211
collector.grpc.stat.port=9992
collector.grpc.span.ip=192.168.254.211
collector.grpc.span.port=9993
collector.grpc.discardpolicy.maxpendingthreshold=10000

[Common]
Web_Port=80
Log_Level=DEBUG
LOG_DIR=/backup/demoapp/pinpoint-c-agent/logs/

[Agent]
Address=/tmp/collector-agent.sock

**Index.php**
require_once __DIR__. "/vendor/autoload.php";
define('AOP_CACHE_DIR',__DIR__.'/Cache/');
define('PLUGINS_DIR',__DIR__.'/Plugins/');
define('APPLICATION_NAME','PHP-DEMO');
define('APPLICATION_ID','PHP-DEMO');

function pinpoint_user_class_loader_hook()
{
    Yii::$enableIncludePath = false;
    $loaders = spl_autoload_functions();
    foreach ($loaders as $loader) {
        if(is_array($loader) && is_string($loader[0]) && $loader[0] =='YiiBase'){
            spl_autoload_unregister($loader);
            spl_autoload_register(['Plugins\PinpointYiiClassLoader','autoload'],true,false);
            break;
        }
    }
}

pinpoint_user_class_loader_hook();
require_once __DIR__. '/vendor/naver/pinpoint-php-aop/auto_pinpointed.php';

**Comment by eeliu** [comment]
@pradeepgunsgmail 

Share the error output to us.

**Comment by marty-macfly** [comment]
I'm trying also to use pinpoint on a Yii application, and I've got the following:

```
Fatal error: Uncaught LogicException: Passed array does not specify an existing static method (class '\Plugins\PinpointYiiClassLoader' not found) in /app/web/index.php:24 Stack trace: #0 /app/web/index.php(24): spl_autoload_register(Array, true, false) #1 /app/web/index.php(30): pinpoint_user_class_loader_hook() #2 {main} thrown in /app/web/index.php on line 24
```

**Comment by eeliu** [comment]
@marty-macfly 
Check this file https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/Example/PHP/demo/yii-demo/Plugins/PinpointYiiClassLoader.php#L22

**Comment by marty-macfly** [comment]
What I've done:

```
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
```

```sh
root@8c7b33aef1fe:/app# ls -l
total 296
drwxr-xr-x  2 1000  985   4096 Oct 27 07:50 Cache
-rw-r--r--  1 1000  985    422 Oct 27 07:57 Dockerfile
-rw-r--r--  1 1000  985   1524 Sep 14 22:06 LICENSE.md
drwxr-xr-x  2 1000  985   4096 Oct 27 07:50 Plugins
-rw-r--r--  1 1000  985   7571 Sep 14 22:06 README.md
-rw-r--r--  1 1000  985   3003 Sep 14 22:06 Vagrantfile
drwxr-xr-x  2 1000  985   4096 Sep 14 22:06 assets
-rw-r--r--  1 1000  985    571 Sep 14 22:06 codeception.yml
drwxr-xr-x  2 1000  985   4096 Sep 14 22:06 commands
-rw-r--r--  1 1000  985   2348 Oct 27 07:53 composer.json
-rw-r--r--  1 1000  985 185691 Oct 27 07:29 composer.lock
drwxr-xr-x  2 1000  985   4096 Sep 14 22:06 config
drwxr-xr-x  2 1000  985   4096 Sep 14 22:06 controllers
-rw-r--r--  1 1000  985    581 Oct 27 07:40 docker-compose.yml
drwxr-xr-x  3 1000  985   4096 Sep 14 22:06 mail
drwxr-xr-x  2 1000  985   4096 Sep 14 22:06 models
-rw-r--r--  1 1000  985    136 Oct 27 07:44 pinpoint.ini
-rw-r--r--  1 1000  985   5860 Sep 14 22:06 requirements.php
drwxrwxr-x  4 root root   4096 Oct 27 07:47 runtime
drwxr-xr-x  9 1000  985   4096 Sep 14 22:06 tests
drwxr-xr-x  5 1000  985   4096 Sep 14 22:06 vagrant
drwxr-xr-x 27 1000  985   4096 Oct 27 07:29 vendor
drwxr-xr-x  4 1000  985   4096 Sep 14 22:06 views
drwxr-xr-x  5 1000  985   4096 Oct 27 07:50 web
drwxr-xr-x  2 1000  985   4096 Sep 14 22:06 widgets
-rwxr-xr-x  1 1000  985    553 Sep 14 22:06 yii
-rw-r--r--  1 1000  985    515 Sep 14 22:06 yii.bat
```


* Copy file from [Example/PHP/demo/yii-demo/Plugins](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/Example/PHP/demo/yii-demo/Plugins) into `basic/`

```sh
root@8c7b33aef1fe:/app# ls -l Plugins/
total 36
-rw-r--r-- 1 1000 985 1427 Oct 27 07:50 Candy.php
-rw-r--r-- 1 1000 985 1426 Oct 27 07:50 CommonPlugin.php
-rw-r--r-- 1 1000 985 4345 Oct 27 07:50 NextSpanPlugin.php
-rw-r--r-- 1 1000 985 5619 Oct 27 07:50 PerRequestPlugins.php
-rw-r--r-- 1 1000 985 1601 Oct 27 07:50 PinpointYiiClassLoader.php
-rw-r--r-- 1 1000 985 1595 Oct 27 07:50 PluginsDefines.php
-rw-r--r-- 1 1000 985 3063 Oct 27 07:50 YiiPerRequestPlugin.php
```
* Copy [index.php](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/Example/PHP/demo/yii-demo/web/index.php) into `basic/web/`

```php
root@8c7b33aef1fe:/app# cat web/index.php 
<?php

// comment out the following two lines when deployed to production
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/../config/web.php';
///////////////Setting of pinpoint php////////////////////
//Cached class
define('AOP_CACHE_DIR',__DIR__.'/../Cache/');
// where to load pinpoint plugins
define('PLUGINS_DIR',__DIR__.'/../Plugins/');

define('APPLICATION_NAME','APP-yii');
define('APPLICATION_ID','app-yii');
// 
/**
 * unregister Yii class loader
 * wrapper with PinpointYiiClassLoader
 */
function pinpoint_user_class_loader_hook()
{
    $loaders = spl_autoload_functions();
    foreach ($loaders as $loader) {
        if(is_array($loader) && is_string($loader[0]) && $loader[0] =='Yii'){
            spl_autoload_unregister($loader);
            spl_autoload_register(['Plugins\PinpointYiiClassLoader','autoload'],true,false);
            break;
        }
    }
}

pinpoint_user_class_loader_hook();


$config = require __DIR__ . '/../config/web.php';
$app = new yii\web\Application($config);
require_once __DIR__. '/../vendor/naver/pinpoint-php-aop/auto_pinpointed.php';

$app->run();
```

* Update `composer.json` to add `autoload` and `require`

```json
root@8c7b33aef1fe:/app# cat composer.json 
{
    "autoload": {
        "psr-4": {
            "Plugins\\": "Plugins/"
        }
    },
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.6.0",
        "yiisoft/yii2": "~2.0.14",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
        "naver/pinpoint-php-aop": "v1.0.1"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.1.0",
        "yiisoft/yii2-gii": "~2.1.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/codeception": "^4.0",
        "codeception/verify": "~0.5.0 || ~1.1.0",
        "codeception/specify": "~0.4.6",
        "symfony/browser-kit": ">=2.7 <=4.2.4",
        "codeception/module-filesystem": "^1.0.0",
        "codeception/module-yii2": "^1.0.0",
        "codeception/module-asserts": "^1.0.0"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset": {
            "enabled": false
        }
    },
    "scripts": {
        "post-install-cmd": [
            "yii\\composer\\Installer::postInstall"
        ],
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject",
            "yii\\composer\\Installer::postInstall"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ]
        },
        "yii\\composer\\Installer::postInstall": {
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
```

* Install pinpoint php module

```sh
root@8c7b33aef1fe:/app# php -i | grep pinpoint 
/usr/local/etc/php/conf.d/pinpoint.ini,
pinpoint_php
pinpoint_php support => enabled
pinpoint_php.CollectorHost => Tcp:192.168.211.1:9994 => Tcp:192.168.211.1:9994
pinpoint_php.DebugReport => no => no
pinpoint_php.TraceLimit => -1  => -1 
pinpoint_php.UnitTest => no => no
```

* Go to `index.php` through browser and get the error

```
Fatal error: Uncaught LogicException: Passed array does not specify an existing static method (class 'Plugins\PinpointYiiClassLoader' not found) in /app/web/index.php:30 Stack trace: #0 /app/web/index.php(30): spl_autoload_register(Array, true, false) #1 /app/web/index.php(36): pinpoint_user_class_loader_hook() #2 {main} thrown in /app/web/index.php on line 30
```

Did I miss something ?

**Comment by marty-macfly** [comment]
In fact composer update didn't install aop properly, re-run it and:

```
  - Installing nikic/php-parser (v4.10.2): Loading from cache
  - Installing naver/pinpoint-php-aop (v1.0.1): Loading from cache
```

**Comment by marty-macfly** [comment]
Now I've got following exception:

```php
yii\base\ErrorException: assert(): assert($itemStartPos &gt;= 0 &amp;&amp; $itemEndPos &gt;= 0 &amp;&amp; $itemStartPos &gt;= $pos) failed in /app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php:759
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'assert(): asser...', '/app/vendor/nik...', 759, Array)
#1 /app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(759): assert(false, 'assert($itemSta...')
#2 /app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(574): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 559, 0, 'Stmt_Namespace', 'stmts', NULL)
#3 /app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(892): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Namespace_), true)
#4 /app/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(492): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 0, 0, 'File', 'stmts', NULL)
#5 /app/vendor/naver/pinpoint-php-aop/lib/pinpoint/Common/OrgClassParse.php(120): PhpParser\PrettyPrinterAbstract->printFormatPreserving(Array, Array, Array)
#6 /app/vendor/naver/pinpoint-php-aop/lib/pinpoint/Common/CodeVisitor.php(162): pinpoint\Common\OrgClassParse->orgClassNodeDoneCB(Array, 'app\\controllers...')
#7 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(94): pinpoint\Common\CodeVisitor->afterTraverse(Array)
#8 /app/vendor/naver/pinpoint-php-aop/lib/pinpoint/Common/OrgClassParse.php(108): PhpParser\NodeTraverser->traverse(Array)
#9 /app/vendor/naver/pinpoint-php-aop/lib/pinpoint/Common/OrgClassParse.php(99): pinpoint\Common\OrgClassParse->parseOriginFile()
#10 /app/vendor/naver/pinpoint-php-aop/lib/pinpoint/Common/PinpointDriver.php(87): pinpoint\Common\OrgClassParse->__construct('/app/controller...', 'app\\controllers...', Array)
#11 /app/vendor/naver/pinpoint-php-aop/auto_pinpointed.php(17): pinpoint\Common\PinpointDriver->init(Object(pinpoint\Common\AopClassMap))
#12 /app/web/index.php(41): require_once('/app/vendor/nav...')
#13 {main}
```

**Comment by eeliu** [comment]
@marty-macfly 

Please rollback php-parser with"nikic/php-parser": "4.10.0".

**Comment by marty-macfly** [comment]
It works (meaning I don't have exception and page display properly), with

```
        "naver/pinpoint-php-aop": "v1.0.1",
        "nikic/php-parser": "v4.10.0"
```

 I'll try later with:

```
 "pinpoint-apm/pinpoint-php-aop": "dev-dev"
```

**Comment by marty-macfly** [comment]
I'm doing more test and I'm having a look on the example [plugin](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/Example/PHP/demo/yii-demo/Plugins) and it seems that the `PerRequestPlugins.php` is doing exactly the same as `YiiPerRequestPlugin.php` and the second one is in fact not used. Is that correct ?

**Comment by eeliu** [comment]
@marty-macfly 

Yes，you are right. These duplicated files could be merged into same file in the next version.

**Comment by marty-macfly** [comment]
Ok, thanks

In the [Plugins/CommonPlugin.php](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/master/Example/PHP/demo/yii-demo/Plugins/CommonPlugin.php) it hooks on `controllers\SiteController::behaviors`, `app\controllers\SiteController::actions`, `app\controllers\SiteController::actionIndex`, `app\controllers\SiteController::actionLogin` is their a method to wildcard hook on all method instead of listing of all them ?

Something like that to hook all method of the controller
```
///@hook:controllers\SiteController
```
 Or like

```
///@hook:controllers\SiteController::*
```
Or the method to explicitly list all controller and all the method ?

**Comment by eeliu** [comment]
@marty-macfly 

Hmm, it not support hook `all the methods`!  Only hooks the method/function you cared!

**Comment by marty-macfly** [comment]
Ok, I'm trying the following, in basic yii application I've add in `controllers/SiteController.php`

```php
    public function actionIndex()
    {
        $db = new \yii\db\Connection([
            'dsn' => 'mysql:host=mysql;dbname=yii2basic',
            'username' => 'root',
            'password' => 'test',
            'charset' => 'utf8',    
        ]);
        $db->open();
        $db->createCommand('SELECT NOW()')->queryAll();
        $db->close();
}
```

In the plugin I had `Plugins/DbPlugin.php`

```php
<?php

namespace Plugins;
// https://github.com/yiisoft/yii2/blob/master/framework/db/Connection.php

///@hook:yii\db\Connection::open
///@hook:yii\db\Command::query
///@hook:yii\db\Connection::close
class DbPlugin extends Candy
{
    function onBefore()
    {
        //pinpoint_add_clue("stp", MYSQL);
        pinpoint_add_clue("stp", PHP_METHOD);
        pinpoint_add_clue("dst", $this->who->dsn);
        pinpoint_add_clues(PHP_ARGS, 'plop');
    }

    function onEnd(&$ret)
    {
        pinpoint_add_clues(PHP_RETURN, print_r($this->ret, true));
    }

    function onException($e)
    {
        pinpoint_add_clue("EXP",$e->getMessage());
    }
}
```

In the pinpoint I see:

![image](https://user-images.githubusercontent.com/12715929/98087623-f64a2b80-1eb2-11eb-9ee4-2567da4aedc1.png)

No trace of the `yii\db\Connection::open`, `yii\db\Connection::close` and `yii\db\Command::query`

Inside the yii debug panel we can see the use of the proxied version

![image](https://user-images.githubusercontent.com/12715929/98087747-2691ca00-1eb3-11eb-8563-9a9fc1a6a423.png)

what am I missing ?

**Comment by marty-macfly** [comment]
I've done the same kind of thing for Redis and it works properly I can see the trace and the Redis component inside pinpoint.

**Comment by eeliu** [comment]
Fellow this file 
https://github.com/pinpoint-apm/pinpoint-c-agent/blob/c8cfbbf524adc891a87d1dba389b37b7f6dbc300/Example/PHP/demo/Flarum-demo/Plugins/DBPlugin.php#L37

**Comment by marty-macfly** [comment]
Doesn't change anything still the same trace on pintpoint ui, it seems in fact that the code is not run.

**Comment by eeliu** [comment]
@marty-macfly 

 Hmm, I can't address the problem from `DbPlugin`. 

pinpoint-php-aop, it wrappers the class before it loading. In other word, it can't wrapper a loaded class. 

Share your project to us if it's possible.

**Comment by marty-macfly** [comment]
Here is the sample project [basic.tar.gz](https://github.com/pinpoint-apm/pinpoint-c-agent/files/5504255/basic.tar.gz)

**Comment by eeliu** [comment]
@marty-macfly 

Update your /web/index.php

``` php
$config = require __DIR__ . '/../config/web.php';
require_once __DIR__. '/../vendor/naver/pinpoint-php-aop/auto_pinpointed.php';  // <---- pull this line out of the yii\web\Application
$app = new yii\web\Application($config);
$app->run();
```

The `Connection.php` is in control.

**Comment by marty-macfly** [comment]
Thanks, make sense need to override class before instantiate the application.

**Comment by marty-macfly** [comment]
I've done more test to be able to instrument HTTP request, to instrument CLI.

I've got one more use case that for the moment is not working as expected. I've got long running CLI (in fact daemon worker that proceed messages) so they never end with the current method of PerRequestPlugins.php no information is ever sent to pinpoint collector, is it possible to regularly flush the data so trace are sent. In fact is how to handle that use case ?

**Comment by eeliu** [comment]
@marty-macfly 

I think up 2 cases

1.  A fetal error in your script
2. The connection between php-fpm and collector-agent is not ready

While, the delayed data will pass to collector in next request.

**Comment by marty-macfly** [comment]
It's not a php-fpm process, it's CLI that connect to a Redis and proceed message and the CLI never end (so the request never end). The workaround I've found so far it's to artificially force the end of the request and start a new in the middle of the code. Like that:

```php
<?php

namespace Plugins;

///@hook:yii\queue\cli\Queue::handleMessage
class QueuePlugin extends Candy
{
    protected $app_name;
    protected $app_id;
    protected $tid;
    protected $psid;

    public function __construct($apId, $who, &...$args)
    {
        $argv = isset($_SERVER['argv']) ? implode(" ", $_SERVER['argv']) : '';

        // Special behavior for never ending worker
        if (preg_match('/\/listen.+--isolate\s+0/', $argv) === 1)
        {
            $this->app_name = PerRequestPlugins::instance()->app_name;
            $this->app_id = PerRequestPlugins::instance()->app_id;
            $this->tid = PerRequestPlugins::instance()->tid;
            $this->psid = PerRequestPlugins::instance()->sid;

            // End all previous started tracing
            while (pinpoint_end_trace() > 0);

            pinpoint_start_trace();
            pinpoint_add_clue("stp", PHP);
            pinpoint_add_clue("name", "PHP Request: ". php_sapi_name());
            pinpoint_add_clue("server", $argv);
            pinpoint_add_clue("uri", sprintf("[id:%s] %s", $args[0], $argv));
            pinpoint_add_clue("appname", $this->app_name);
            pinpoint_add_clue("tid", PerRequestPlugins::instance()->generateTransactionID());
            pinpoint_add_clue("sid", PerRequestPlugins::instance()->generateSpanID());
            pinpoint_add_clue('appid', $this->app_id);
        }

        array_unshift($args, $apId, $who);
        call_user_func_array('parent::__construct', $args);
    }

    public function __destruct()
    {
        if (isset($this->tid))
        {
            while (pinpoint_end_trace() > 1);
        }
        parent::__destruct();
    }

    function onBefore()
    {
        pinpoint_add_clue("stp", PHP_METHOD);
        pinpoint_add_clues(PHP_ARGS, sprintf("[id:%s][ttr:%s][attempt:%s]", $this->args[0], $this->args[2], $this->args[3]));
    }

    function onEnd(&$ret)
    {
        pinpoint_add_clues(PHP_RETURN, print_r($ret, true));
    }

    function onException($e)
    {
        pinpoint_add_clue("EXP", $e->getMessage());
    }
}
```

But in that case I loose the link between the initial trace (the cli startup trace), to work around that I've tried to link all trace with `pinpoint_add_clue("psid", ....);` but it doesn't seems to work in the UI side.

**Comment by eeliu** [comment]
@marty-macfly   https://github.com/pinpoint-apm/pinpoint-c-agent/issues/221#issuecomment-731036071
Does your cli, run in asyn or syn? 
If syn, the lifecycle of `QueuePlugin` must binded on every message. 
While, if in asyn, current version not support! Checkc the [aync version](https://github.com/pinpoint-apm/pinpoint-c-agent/blob/async_api/src/PHP/pinpoint_php_api.php) .

**Comment by eeliu** [comment]
It looks your pinpoint works fine.
