### ISSUE TITLE
[pinpoint collector agent] Error `INVALID_ARGUMENT: invalid agentid`

### ISSUE THREAD

**Issue by marty-macfly** [pinpoint-apm/pinpoint-c-agent#283]
I'm having the following error on collector agent side, about agent id not valid, is there a maximum length for agentid name or some forbidden characters ?

```
[2021-01-08 12:38:59,689] [29] [INFO] [AppManagement.py:57] collector-agent try to create a new application agent.[sid.salt-data-event-listen@sid@1500]
--
  | [2021-01-08 12:38:59,718] [29] [INFO] [AppManagement.py:57] collector-agent try to create a new application agent.[sid.salt-job-event-listen@sid@1500]
  | [2021-01-08 12:38:59,778] [35] [WARNING] [GrpcStat.py:65] SendAgentStat met:<_InactiveRpcError of RPC that terminated with:
  | status = StatusCode.INVALID_ARGUMENT
  | details = "INVALID_ARGUMENT: invalid agentid"
  | debug_error_string = "{"created":"@1610109539.774057069","description":"Error received from peer ipv4:192.168.10.27:9992","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"INVALID_ARGUMENT: invalid agentid","grpc_status":3}"
  | >
```

I'm using collector agent version 0.4.1

**Comment by marty-macfly** [comment]
I can see the error on collector side:

```

01-08 12:40:39.039 [cAgent-Server-5] INFO  c.n.p.g.s.HeaderPropagationInterceptor   : Header extract fail cause=INVALID_ARGUMENT: invalid agentid, method=v1.ProfilerCommandService/HandleCommand headers=Metadata(starttime=1610109490855,agentid=sid.salt-data-event-listen,applicationname=sid,socketid=1,starttime=1610109490855,agentid=sid.salt-data-event-listen,applicationname=sid,socketid=1,content-type=application/grpc,user-agent=grpc-python/1.34.0 grpc-c/14.0.0 (linux; chttp2),grpc-accept-encoding=identity,deflate,gzip,accept-encoding=identity,gzip), attr={remote-addr=/10.131.2.1:47164, io.grpc.internal.GrpcAttributes.securityLevel=NONE, transportMetadata=DefaultTransportMetadata{debugString='grpcAgentReceiver', remoteAddress=/10.131.2.1:47164, transportId=159, connectTime=1610109539928}, local-addr=/10.129.2.110:9991}
--
  | io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid agentid
  | at io.grpc.Status.asRuntimeException(Status.java:524) ~[grpc-api-1.33.1.jar!/:1.33.1]
  | at com.navercorp.pinpoint.grpc.server.AgentHeaderReader.validateId(AgentHeaderReader.java:110) ~[pinpoint-grpc-2.2.0.jar!/:2.2.0]
  | at com.navercorp.pinpoint.grpc.server.AgentHeaderReader.getId(AgentHeaderReader.java:68) ~[pinpoint-grpc-2.2.0.jar!/:2.2.0]
  | at com.navercorp.pinpoint.grpc.server.AgentHeaderReader.extract(AgentHeaderReader.java:41) ~[pinpoint-grpc-2.2.0.jar!/:2.2.0]
  | at com.navercorp.pinpoint.grpc.server.AgentHeaderReader.extract(AgentHeaderReader.java:34) ~[pinpoint-grpc-2.2.0.jar!/:2.2.0]
  | at com.navercorp.pinpoint.grpc.server.HeaderPropagationInterceptor.interceptCall(HeaderPropagationInterceptor.java:55) [pinpoint-grpc-2.2.0.jar!/:2.2.0]
  | at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244) [grpc-api-1.33.1.jar!/:1.33.1]
  | at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:648) [grpc-core-1.33.1.jar!/:1.33.1]
  | at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:626) [grpc-core-1.33.1.jar!/:1.33.1]
  | at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1900(ServerImpl.java:416) [grpc-core-1.33.1.jar!/:1.33.1]
  | at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInternal(ServerImpl.java:557) [grpc-core-1.33.1.jar!/:1.33.1]
  | at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:532) [grpc-core-1.33.1.jar!/:1.33.1]
  | at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.33.1.jar!/:1.33.1]
  | at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.33.1.jar!/:1.33.1]
  | at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:109) [classes!/:2.2.0]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
  | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by marty-macfly** [comment]
I think I've got my reply  #1884 it's 24 by default. I'm not an hbase expert so is there an easy to increase it #4312 ?
