### ISSUE TITLE
No data in pinpoint web, Laravel App, docker environment

### ISSUE THREAD

**Issue by rightphp** [pinpoint-apm/pinpoint-c-agent#313]
I have got php-fpm, pinpoint-agent, rest of pinpoint docker images are connected and working.

The problem I am facing is there are errors in my php application built in Laravel but those erros are not visible in pinpoint.

This is my php.ini

```
; PHP Configuration
; Error handling
display_errors = On

;Pinpoint collector agent
extension=pinpoint_php.so
; Collector-agent's TCP address, ip,port:Collector-Agent's ip,port, please insure it consistent with that in step2(Build Collector-Agent).
pinpoint_php.CollectorHost=Tcp:phpcol:9999
; or unix:(unix sock address)
;pinpoint_php.CollectorHost=unix:/tmp/collector-agent.sock
pinpoint_php.SendSpanTimeOutMs=0 # 0 is recommanded
; request should be captured duing 1 second. < 0 means no limited
pinpoint_php.TraceLimit=-1 

; DEBUG the agent, PHP's log_error should turn on too.
pinpoint_php.DebugReport=true
error_reporting = E_ALL
log_errors = On
error_log = /tmp/php_fpm_error.log
```

I logged into php-fpm container and following is the tail content of /tmp/php_fpm_error.log
```
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#0 pinpoint_start start
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clue key:uri value:/api/login
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clue key:client value:172.20.0.1
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clue key:server value:automation.local
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clue key:stp value:1500
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clue key:name value:PHP Request
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clue key:appname value:Local-Automation
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clue key:appid value:local-automation-1
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clue key:tid value:local-automation-1^1612280245478^7
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clue key:sid value:1011135359
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 add clues:46:500
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]this span:({"E":110,"FT":1500,"S":1612282465376,"appid":"local-automation-1","appname":"Local-Automation","client":"172.20.0.1","clues":["46:500"],"name":"PHP Request","server":"automation.local","sid":"1011135359","stp":"1500","tid":"local-automation-1^1612280245478^7","uri":"/api/login"})
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]4 send size 287
[02-Feb-2021 16:14:25 UTC] [pinpoint] [8] [8]#128 pinpoint_end_trace Done!
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#0 pinpoint_start start
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clue key:uri value:/api/login
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clue key:client value:172.20.0.1
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clue key:server value:automation.local
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clue key:stp value:1500
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clue key:name value:PHP Request
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clue key:appname value:Local-Automation
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clue key:appid value:local-automation-1
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clue key:tid value:local-automation-1^1612280245478^8
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clue key:sid value:567885562
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 add clues:46:500
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]this span:({"E":224,"FT":1500,"S":1612282466439,"appid":"local-automation-1","appname":"Local-Automation","client":"172.20.0.1","clues":["46:500"],"name":"PHP Request","server":"automation.local","sid":"567885562","stp":"1500","tid":"local-automation-1^1612280245478^8","uri":"/api/login"})
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]4 send size 286
[02-Feb-2021 16:14:26 UTC] [pinpoint] [7] [7]#128 pinpoint_end_trace Done!
```

on same php-fpm container there are errors in laravel.log
```
root@9a45760f608e:/var/www/html/reports.thirdrepublic.com/storage/logs# ls -la
total 679
drwxrwxrwx 1 root root      0 Nov  6 11:32 .
drwxrwxrwx 1 root root      0 Nov 24 07:45 ..
-rwxr-xr-x 1 root root     16 Nov  6 10:01 .gitignore
-rwxr-xr-x 1 root root 694400 Feb  2 16:14 laravel.log
root@9a45760f608e:/var/www/html/reports.thirdrepublic.com/storage/logs# tail laravel.log
#49 /var/www/html/reports.thirdrepublic.com/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/html/reports.thirdrepublic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/html/reports.thirdrepublic.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/html/reports.thirdrepublic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/www/html/reports.thirdrepublic.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/html/reports.thirdrepublic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 /var/www/html/reports.thirdrepublic.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#56 /var/www/html/reports.thirdrepublic.com/public/index.php(63): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#57 {main}
"}
```

This is what I have put in index.php of my laravel app

```
require __DIR__.'/../vendor/autoload.php';
#####################################################3
define('APPLICATION_NAME','Local-Automation');
define('APPLICATION_ID','local-automation-1');
define('AOP_CACHE_DIR',__DIR__.'/../Cache/');
define('PLUGINS_DIR',__DIR__.'/../Plugins/');
define('PINPOINT_USE_CACHE','YES');
define('PP_REQ_PLUGINS', '\Plugins\PerRequestPlugins');
#define('USER_DEFINED_CLASS_MAP_IMPLEMENT',"\Plugins\Framework\app\ClassMapInFile");
require_once __DIR__. '/../vendor/pinpoint-apm/pinpoint-php-aop/auto_pinpointed.php';
#####################################################3
```

I went to collector agent and tried to find out errors in case of any but seems ot be no error over there

```
D:\GitRepos\docker\docker-nginx-php-mysql>docker exec -it phpcol bash
root@5133995ee24a:/CollectorAgent# cd /tmp/
root@5133995ee24a:/tmp# ls -la
total 8
drwxrwxrwt 1 root root 4096 Feb  2 15:37 .
drwxr-xr-x 1 root root 4096 Feb  2 15:37 ..
-rw-r--r-- 1 root root    0 Feb  2 15:37 collector.agent.log
-rw-r--r-- 1 root root    0 Feb  2 15:37 front.agent.log
```

please suggest what I am doing wrong?

**Comment by eeliu** [comment]
> -rw-r--r-- 1 root root    0 Feb  2 15:37 collector.agent.log

Change collector-agent log level to DEBUG and share `collector.agent.log`  during some requests.

**Comment by rightphp** [comment]
@eeliu following are the logs of that file now

```
[2021-02-03 06:27:55,424] [8] [DEBUG] [GrpcAgent.py:202] agentclient: hostname:62478033a97e ip:172.20.0.8  pid:8 address:pinpoint-collector:9991 send ping
[2021-02-03 06:27:55,426] [8] [DEBUG] [GrpcAgent.py:192] get ping response: agentinfo:[('starttime', '1612333632129'), ('agentid', 'local-automation-1'), ('applicationname', 'Local-Automation'), ('socketid', '1')]
[2021-02-03 06:28:00,417] [8] [DEBUG] [GrpcStat.py:51] agentStat {
  timestamp: 1612333680417
  collectInterval: 30
  gc {
    type: JVM_GC_TYPE_CMS
  }
  cpuLoad {
    systemCpuLoad: 0.057
  }
  responseTime {
  }
}

[2021-02-03 06:28:05,419] [8] [DEBUG] [GrpcStat.py:51] agentStat {
  timestamp: 1612333685419
  collectInterval: 30
  gc {
    type: JVM_GC_TYPE_CMS
  }
  cpuLoad {
    systemCpuLoad: 0.047
  }
  responseTime {
  }
}

[2021-02-03 06:28:10,422] [8] [DEBUG] [GrpcStat.py:51] agentStat {
  timestamp: 1612333690422
  collectInterval: 30
  gc {
    type: JVM_GC_TYPE_CMS
  }
  cpuLoad {
    systemCpuLoad: 0.063
  }
  responseTime {
  }
}

[2021-02-03 06:28:15,425] [8] [DEBUG] [GrpcStat.py:51] agentStat {
  timestamp: 1612333695425
  collectInterval: 30
  gc {
    type: JVM_GC_TYPE_CMS
  }
  cpuLoad {
    systemCpuLoad: 0.061
  }
  responseTime {
  }
}

[2021-02-03 06:28:20,429] [8] [DEBUG] [GrpcStat.py:51] agentStat {
  timestamp: 1612333700429
  collectInterval: 30
  gc {
    type: JVM_GC_TYPE_CMS
  }
  cpuLoad {
    systemCpuLoad: 0.066
  }
  responseTime {
  }
}

[2021-02-03 06:28:25,433] [8] [DEBUG] [GrpcStat.py:51] agentStat {
  timestamp: 1612333705434
  collectInterval: 30
  gc {
    type: JVM_GC_TYPE_CMS
  }
  cpuLoad {
    systemCpuLoad: 0.057
  }
  responseTime {
  }
}

[2021-02-03 06:28:30,436] [8] [DEBUG] [GrpcStat.py:51] agentStat {
  timestamp: 1612333710437
  collectInterval: 30
  gc {
    type: JVM_GC_TYPE_CMS
  }
  cpuLoad {
    systemCpuLoad: 0.06
  }
  responseTime {
  }
}

[2021-02-03 06:28:35,439] [8] [DEBUG] [GrpcStat.py:51] agentStat {
  timestamp: 1612333715440
  collectInterval: 30
  gc {
    type: JVM_GC_TYPE_CMS
  }
  cpuLoad {
    systemCpuLoad: 0.047
  }
  responseTime {
  }
}

[2021-02-03 06:28:40,442] [8] [DEBUG] [GrpcStat.py:51] agentStat {
  timestamp: 1612333720442
  collectInterval: 30
  gc {
    type: JVM_GC_TYPE_CMS
  }
  cpuLoad {
    systemCpuLoad: 0.053
  }
  responseTime {
  }
}
```

**Comment by rightphp** [comment]
![image](https://user-images.githubusercontent.com/8712458/106707979-291dd000-6618-11eb-9015-e498419eecab.png)

**Comment by eeliu** [comment]
@rightphp 
php/python does not have such chat as java agent.

**Comment by rightphp** [comment]
@eeliu so what does that mean? I wont be able to see the php error logs into pinpoint?

**Comment by eeliu** [comment]
@rightphp 

1. Does the server-map works?
2. How about the php call stack?

You can get the errror/exception information from callstack.

**Comment by rightphp** [comment]
How do I diagnose that?

Checking server-map and php call stack?

**Comment by rightphp** [comment]
update please

**Comment by rightphp** [comment]
There were errors but not showing errors and no transaction data for successful transaction as well as you can see in previous screen shot

![image](https://user-images.githubusercontent.com/8712458/106761241-a0745380-665a-11eb-89f9-ec261b8011d9.png)

**Comment by rightphp** [comment]
![image](https://user-images.githubusercontent.com/8712458/106761460-da455a00-665a-11eb-8567-e70678ecf42c.png)

**Comment by eeliu** [comment]
@rightphp 

No plugins to trace transaction, while you can give us a PR.

**Comment by rightphp** [comment]
How to give PR?
