### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by eeliu** [pinpoint-apm/pinpoint-c-agent#658]
**Describe the bug**

```
2024.08.01T02:57:12.796panic: send on closed channel
2024.08.01T02:57:12.796goroutine 38 [running]:
2024.08.01T02:57:12.796github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/agent.(*SpanSender).Interceptor(0xc0002bc1e8, 0xc0005a4180?)
2024.08.01T02:57:12.796	/apps/agent/SpanSender.go:344 +0x165
2024.08.01T02:57:12.796github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/agent.(*GrpcAgent).consumeJsonSpan(0xc0002bc180)
2024.08.01T02:57:12.796	/apps/agent/GrpcAgent.go:458 +0x1c9
2024.08.01T02:57:12.796created by github.com/pinpoint-apm/pinpoint-c-agent/collector-agent/agent.(*GrpcAgent).Start
2024.08.01T02:57:12.796	/apps/agent/GrpcAgent.go:311 +0x56

```

**Comment by eeliu** [comment]
## Reason

It was caused from undefined order when closing span stream.
